FROM python:3.11-slim

WORKDIR /app

COPY app/dmp-service/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -U pip && pip install --no-cache-dir -r /app/requirements.txt

COPY app/dmp-service/app.py /app/app.py

CMD ["python", "-u", "/app/app.py"]